"""Add stickies

Revision ID: 284db2647b9
Revises: 2bf684f40b9
Create Date: 2015-08-06 22:56:16.092904

"""

# revision identifiers, used by Alembic.
revision = '284db2647b9'
down_revision = '2bf684f40b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('sticky', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'sticky')
    ### end Alembic commands ###
